#Equazione di Bellman in pratica

##Inizializzazione delle matrici

In [1]:
import numpy as np

def initialize_matrices(n_states, n_actions):
    # Initialize the reward matrix (n_states x n_actions)
    R = np.zeros((n_states, n_actions))
    R[n_states - 1][n_actions - 1] = 1.0
    # Initialize the value matrix (n_states)
    V = np.zeros(n_states)

    return R, V

##Aggiornamento dei valori seguendo l'equazione di Bellman

In [2]:
def bellman_update(V, R, gamma, n_iterations):
    n_states, n_actions = R.shape
    for _ in range(n_iterations):
        V_new = np.copy(V)
        for s in range(n_states):
            V_new[s] = max([R[s, a] + gamma * V[a] for a in range(n_actions)])
        V = V_new
    return V

##Esempio

In [3]:
n_states = 5
n_actions = 5
gamma = 0.9
n_iterations = 1

R, V = initialize_matrices(n_states, n_actions)


###Stampa della reward matrix

In [4]:
print("Initial Reward Matrix (R):")
print(R)

Initial Reward Matrix (R):
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]


###Stampa della value matrix

In [5]:
print("\nInitial Value Matrix (V):")
print(V)



Initial Value Matrix (V):
[0. 0. 0. 0. 0.]


###Aggiornamento Value matrix

In [6]:
# Perform Bellman updates
V = bellman_update(V, R, gamma, n_iterations)

# Print the updated value matrix
print("\nUpdated Value Matrix (V):")
print(V)


Updated Value Matrix (V):
[0. 0. 0. 0. 1.]
